max_items_per_category = 10

[[categories]]
name = "國際"
feeds = [
  "https://feeds.feedburner.com/rsscna/intworld",
]

[[categories]]
name = "財經"
feeds = [
  "https://feeds.feedburner.com/rsscna/finance",
]
